### ISSUE TITLE
Feature request: SCSS & mini-css-extract-plugin support?

### ISSUE THREAD

**Issue by weilinzung** [nuxt/friendly-errors-webpack-plugin#5]
Feature request: SCSS & mini-css-extract-plugin support?

Currently, also all showing loader errors when has the synax error.

![57949725-35498300-78b3-11e9-8bf1-c0e5b56cd4a8](https://user-images.githubusercontent.com/7368063/58059355-7a331b00-7b3a-11e9-9da8-c07c45fe7f4a.png)

**Comment by BryceBarbara** [comment]
It looks like this might not be related to the `friendly-errors-webpack-plugin` which is what this repository is only about. 

As far as your question, I'm not going to be able to troubleshoot anything but I can point you in the right direction. Sass support _should_ be possible simply by [extending the webpack config](https://nuxtjs.org/api/configuration-build#extend) with the following code:

```js
config.module.rules.push({
    loader: "sass-loader",
    test: /\.scss$/,
});
```
